### ISSUE TITLE
Threading issue in Attenuation filter with TBB MultiThreader

### ISSUE THREAD

**Issue by dzenanz** [KitwareMedical/ITKUltrasound#185]
Trying to run example https://github.com/KitwareMedical/ITKUltrasound/blob/master/examples/RFPowerSpectraAttenuation.ipynb locally, with up to date ITKUltrasound at 814944b9d9184478241bf438054c8486e998fd38 the "Metric Image of Attenuations in Liver" and its accompanying mask change from run to run, and all look wrong. Example:
<img width="343" alt="Screenshot 2022-03-11 17 22 36" src="https://user-images.githubusercontent.com/1792121/157980741-37e7cb6a-9f2f-4a0d-820b-5529087f6a82.png">

The result looks as expected if the following line is added right after filter instantiation:
```py
attenuation_filter.SetNumberOfWorkUnits(1)
```

**Comment by tbirdso** [comment]
@dzenanz After rebuilding from [https://github.com/KitwareMedical/ITKUltrasound/commit/814944b9d9184478241bf438054c8486e998fd38](https://github.com/KitwareMedical/ITKUltrasound/commit/814944b9d9184478241bf438054c8486e998fd38) I am unable to recreate the threading issue on Windows 10 with Python 3.8 so far over a range from 1 to 200 work units. Could you please provide platform details as well as the number of work units you are observing the filter to use when the issue occurs? Thanks!

**Comment by dzenanz** [comment]
Up-to-date Windows 10 x64. `ITKUltrasound` 814944b9d9184478241bf438054c8486e998fd38. Recent `ITK`, possibly [8f8debd](https://github.com/InsightSoftwareConsortium/ITK/commit/8f8debd9b6172b9b369fad84196f9b9d2d3cbd16).

Jupyter notebook info:
```text
The version of the notebook server is: 6.0.3
The server is running on this version of Python:
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

Current Kernel Information:
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by dzenanz** [comment]
More computer information:
```text
Edition	Windows 10 Pro
Version	21H2
Installed on	‎2020-‎07-‎14
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0
```
CPU: AMD Ryzen 7 PRO 1700 Eight-Core Processor
Installed RAM	32.0 GB

**Comment by tbirdso** [comment]
Thank you @dzenanz , maybe this is somehow an issue in Python 3.7 packages?

Could you please let me know if we are both starting from 48 work units by default?
```py
>>> attenuation_filter.GetNumberOfWorkUnits()
```

**Comment by dzenanz** [comment]
```py
print(f'NumberOfWorkUnits: {attenuation_filter.GetNumberOfWorkUnits()}')
print(f'Threader: {attenuation_filter.GetMultiThreader()}')
```
which gives
```text
NumberOfWorkUnits: 256
Threader: TBBMultiThreader (00000167BCEBCDF0)
```
But if I add `attenuation_filter.SetMultiThreader(itk.PoolMultiThreader.New())`, then I get:
```text
NumberOfWorkUnits: 64
Threader: PoolMultiThreader (00000167BFFBF040)
```
and results are as expected.

**Comment by tbirdso** [comment]
🤔 Interesting. Do you / should I build ITK with `Module_ITKTBB=ON`? It looks like it is set to OFF by default on my system but if I recall correctly we are typically building Windows Python packages with TBB.

**Comment by tbirdso** [comment]
`itk.AttenuationImageFilter` uses an ITK region splitter to ensure that scan lines are not split over different threads. Perhaps the TBB multithreader is not taking the splitter into account?
