### ISSUE TITLE
Doppler imaging 

### ISSUE THREAD

**Issue by Remo12392** [KitwareMedical/ITKUltrasound#230]
Is there any example in itk-ultrasound defined for doppler imaging.?

I have seen one example SpectralDistributions using GetFFTSpectra function. Is this can be taken as an example for doppler imaging ?

**Comment by dzenanz** [comment]
ITKUltrasound has not been used specifically for doppler imaging analysis to date. That processing relies on spectral analysis and frequency shifting, which the tools in ITKUltrasound are certainly intended to address. We're constantly adding to ITKUltrasound and doppler is something that is on our radar.  We're always interested in funding partners to add functionality.

CC: @tbirdso @brad-t-moore @thewtex

**Comment by Remo12392** [comment]
Thanks for the update
